name: Deep Fuzz
on:
  push:
  pull_request:

jobs:
  deep-fuzz:
    name: Deep Fuzz
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.14.1"
          
      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-d369d2486f85576eec4ca41d277391dfdae21ba7

      - name: Setup Forge
        run: yarn workspace @ubiquity/contracts forge:install

      - name: Deep Fuzz Solidity Contracts      
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
        env:
          FOUNDRY_PROFILE: intense
          run: |
              cd packages/contracts
              pwd
              echo ${{ steps.files.outputs.added_modified }}
              if ${{ github.event_name == 'pull_request' }}:
                forge test
              if ${{ github.event_name == 'push' }}:
                mapfile -d ',' -t files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
                for f in "${files[@]}"; do
                  echo "Do something with this ${f}."
                done
