name: Deep Fuzz
on:
  push:
  pull_request:

jobs:
  deep-fuzz:
    name: Deep Fuzz
    runs-on: ubuntu-22.04
    env:
      FOUNDRY_PROFILE: intense  
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.14.1"
          
      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-d369d2486f85576eec4ca41d277391dfdae21ba7

      - name: Get changed Solidity contracts
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: packages/contracts/src/**

      - name: Deep Fuzz Solidity Contracts
        run: |
          cd packages/contracts
          pwd
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          forge install
          if ${{ github.event_name == 'pull_request' }}; then
            forge test
          fi
          if ${{ github.event_name == 'push' }}; then
            touch fuzz.txt
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              f=$(basename -- $file)
              echo "Searching for $f related tests"
              forge tree | grep -E "^test|^src|${f}" | grep -B1 ${f} | grep ^test | cut -d' ' -f1 >> fuzz.txt
            done
            cat fuzz.txt | sort | uniq -u
          fi
