name: Check diamond facets storage

on:
  push:
    branches:
      - development
  pull_request:

jobs:
  provide_contracts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - id: set-matrix
        working-directory: packages/contracts
        run: |
          echo "contracts"
          echo "::set-output name=matrix::$(forge tree | grep -E "^src/dollar/facets" | cut -d' ' -f1 | xargs basename -s | cut -d'.' -f1)"
          echo $matrix
    
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  check_storage_layout:
    needs: provide_contracts
    runs-on: ubuntu-latest

    strategy:
      matrix:
        contract: ${{ fromJson(needs.provide_contracts.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install storage layout
        uses: Rubilmax/foundry-storage-check@main
